Task01 Екатерина Шелухина HSE
GPGPUCourse/GPGPUTasks2022 pull request #23
Opened 2022-09-26 20:52 UTC by eshelukhina

У меня: 
device name: Intel(R) UHD Graphics 617
Data generated for n=100000000!
Kernel average time: 0.0657092+-0.00679839 s
GFlops: 1.52186
VRAM bandwidth: 3e+08 GB/s
Result data transfer time: 0.105908+-0.019277 s
VRAM -> RAM bandwidth: 3.51747 GB/s
===================
В тестах:

2022-09-27 19:53 UTC, vladimir-nazarenko requested changes
Чувствуется, что писали с душой, приятно читать! Поправьте, пожалуйста, замечания и задача будет зачтена.

2022-09-27 19:53 UTC, vladimir-nazarenko commented on src/cl/aplusb.cl
> +__kernel void aplusb(__global float* a, __global float* b, __global float* c, unsigned int n) {
В cpp данные объявлены как READONLY, так что и здесь лучше их объявить const во избежание ошибок

2022-09-27 19:53 UTC, vladimir-nazarenko commented on src/main.cpp
> +    for (int platformInd = 0; platformInd < platforms.size() && deviceType != CL_DEVICE_TYPE_GPU; ++platformInd) {
Довольно запутанно. Здесь вы можете полагаться, что у пользователя максимум десяток устройств, поэтому вас не волнует асимптотика -- вас волнует качество кода. Как вариант -- собрать std::map<dev_type, vector<device_id>> в одном цикле и дальше сделать один if. Но можете оставить так.

2022-09-27 19:53 UTC, vladimir-nazarenko commented on src/main.cpp
> +        errReleaseContext(errorReleaseContext);
Идея хорошая, но вы здесь удаляете несозданный контекст, так как если при создании контекста произошла ошибка, то он не создан.

2022-09-27 19:53 UTC, vladimir-nazarenko commented on src/main.cpp
> +        switch (errorCreateContext) {
Всё-таки лучше выделить это в функцию, вот такую https://stackoverflow.com/a/24336429/2079157

2022-09-27 19:53 UTC, vladimir-nazarenko commented on src/main.cpp
> +        cl_int errorReleaseQueue = clReleaseCommandQueue(commandQueue);
То же самое про удаление несуществующей очереди

2022-09-27 19:53 UTC, vladimir-nazarenko commented on src/main.cpp
> +        cl_int errorReleaseContext = clReleaseContext(context);
Мысль хорошая -- можно так и оставить, однако в жизни обычно либо у вас c-style error handling, и тогда вместо переписывания кода exit failure path, когда что-то пошло не так и вы хотите освободить ресурсы, как здесь, вы используете goto, либо, раз мы используем c++, у вас всё оборачивается в RAII и бросается исключение. Такое дублирование кода сложно будет поддерживать. В рамках дз можно не думать так сильно о плохих случаях -- если что-то не инициализировалось просто бросать исключение и давать программе сообщить, что случилось, и завершиться -- всё равно мы пока не сможем корректно обработать этот случай.

2022-09-27 19:53 UTC, vladimir-nazarenko commented on src/main.cpp
> +    if (errorCreateBuffer != CL_SUCCESS) {
Выше уже писал -- предлагаю заменить эту обработку просто на OCL_SAFE_CALL.

2022-09-27 19:53 UTC, vladimir-nazarenko commented on src/main.cpp
> +    cl_mem memC = clCreateBuffer(context, CL_MEM_READ_ONLY | CL_MEM_COPY_HOST_PTR, n * sizeof(float), cs.data(),
Опечатка -- этот буфер не может быть readonly, да и копировать его с хоста нам не зачем. Точно нужно поправить

2022-09-27 19:53 UTC, vladimir-nazarenko commented on src/main.cpp
> +    std::vector<char> log(log_size + 1, 0);
Хорошая идея с +1

2022-09-27 19:53 UTC, vladimir-nazarenko commented on src/main.cpp
> +        std::cout << "VRAM bandwidth: " << 3.0 * n + sizeof(float) / (1024 * 1024 * 1024) / t.lapAvg() << " GB/s"
` n + sizeof(float)` -- наверное, имели в виду *

2022-10-02 15:57 UTC, eshelukhina commented on src/cl/aplusb.cl
> +__kernel void aplusb(__global float* a, __global float* b, __global float* c, unsigned int n) {
Исправила

2022-10-02 15:57 UTC, eshelukhina commented on src/main.cpp
> +    for (int platformInd = 0; platformInd < platforms.size() && deviceType != CL_DEVICE_TYPE_GPU; ++platformInd) {
Не стала исправлять :(

2022-10-02 15:57 UTC, eshelukhina commented on src/main.cpp
> +        errReleaseContext(errorReleaseContext);
Исправила все это на OCL_SAFE_CALL

2022-10-02 15:58 UTC, eshelukhina commented on src/main.cpp
> +    cl_mem memC = clCreateBuffer(context, CL_MEM_READ_ONLY | CL_MEM_COPY_HOST_PTR, n * sizeof(float), cs.data(),
Исправила

2022-10-02 15:58 UTC, eshelukhina commented on src/main.cpp
> +        std::cout << "VRAM bandwidth: " << 3.0 * n + sizeof(float) / (1024 * 1024 * 1024) / t.lapAvg() << " GB/s"
Поправила

2022-10-02 19:18 UTC, vladimir-nazarenko commented
Супер, задача зачтена, 5/5.

2022-10-02 19:18 UTC, closed without merging