Task01 Александра Обрядина HSE
GPGPUCourse/GPGPUTasks2022 pull request #30
Opened 2022-09-27 06:08 UTC by xbreathoflife

<details><summary>Локальный вывод</summary><p>

<pre>
Data generated for n=100000000!
Log:

Kernel average time: 0.0291667+-0.000372678 s
GFlops: 3.42857
VRAM bandwidth: 38.3173 GB/s
Result data transfer time: 0.17175+-0.000829156 s
VRAM -> RAM bandwidth: 2.16902 GB/s

Process finished with exit code 0

</pre>
</p></details>

<details><summary>Вывод Github CI</summary><p>
<pre>

</pre>

</p></details>

2022-09-27 20:19 UTC, vladimir-nazarenko requested changes
Отлично написано! Поправьте небольшие замечания и зачтём.

2022-09-27 20:19 UTC, vladimir-nazarenko commented on src/main.cpp
> +    cl_device_id mainDevice = gpuDevice ? gpuDevice : cpuDevice;
Супер, лаконичный, легкочитаемый выбор устройства

2022-09-27 20:19 UTC, vladimir-nazarenko commented on src/main.cpp
> +        std::cout << "Failed to create context with error code: " << context_errcode << std::endl;
Похоже, что мы залогировали, и дальше начинаем использовать невалидный контекст, но у вас аккуратно написано -- как будто бы дальше, если в драйвере никто не ошибся, у вас просто по цепочке всё навернётся и залогируется. Однако не стоит на это полагаться, лучше бросить исключение через OCL_SAFE_CALL прямо здесь

2022-09-27 20:19 UTC, vladimir-nazarenko commented on src/main.cpp
> +    cl_program program = clCreateProgramWithSource(context, 1, &strings, nullptr, &error);
error check

2022-09-30 22:01 UTC, xbreathoflife commented on src/main.cpp
> +        std::cout << "Failed to create context with error code: " << context_errcode << std::endl;
fixed

2022-09-30 22:06 UTC, vladimir-nazarenko commented
Супер, зачтено, 5/5

2022-09-30 22:06 UTC, closed without merging